export const aircraftImages = [
    { key: "a220", image: "a220.png" },
    { key: "a319", image: "a319.png" },
    { key: "a320", image: "a319.png" },
    { key: "a321", image: "a321.png" },
    { key: "a330", image: "a330.png" },
    { key: "a330f", image: "a330f.png" },
    { key: "a330neo", image: "a330neo.png" },
    { key: "a340", image: "a340.png" },
    { key: "a350", image: "a350.png" },
    { key: "a380", image: "a380.png" },
    { key: "e175", image: "e175.png" },
    { key: "e190", image: "e190.png" },
    { key: "tbm-930", image: "tbm930.png" },
    { key: "boeing 717", image: "b717.png" },
    { key: "boeing 737-700", image: "b737-700.png" },
    { key: "boeing 737-800", image: "b737-800.png" },
    { key: "boeing 737-900", image: "b737-900.png" },
    { key: "boeing 737-8 max", image: "b737-8max.png" },
    { key: "boeing 747-200", image: "b747-200.png" },
    { key: "boeing 747-400", image: "b747-400.png" },
    { key: "boeing 747-8", image: "b747-8.png" },
    { key: "boeing 757-200", image: "b757.png" },
    { key: "boeing 767", image: "b767.png" },
    { key: "boeing 777-200ER", image: "b777-200.png" },
    { key: "boeing 777-200LR", image: "b777-200.png" },
    { key: "boeing 777-300ER", image: "b777-300.png" },
    { key: "boeing 787-8", image: "b787-8.png" },
    { key: "boeing 787-9", image: "b787-9.png" },
    { key: "boeing 787-10", image: "b787-10.png" },
    { key: "md-11f", image: "md11f.png" },
  ]

export const emojiCharacterRandomizer = [
  "🤫", "🙃", "🤔", "🤨", "🤯", "🤠", "😲", "🙂‍↕️", "🙂‍↔️", "🥳"
]

export const isoCountryCodes = [
  { key: "Afghanistan 🇦🇫", isoCode: "AF" },
  { key: "Åland Islands 🇦🇽", isoCode: "AX" },
  { key: "Albania 🇦🇱", isoCode: "AL" },
  { key: "Algeria 🇩🇿", isoCode: "DZ" },
  { key: "American Samoa 🇦🇸", isoCode: "AS" },
  { key: "Andorra 🇦🇩", isoCode: "AD" },
  { key: "Angola 🇦🇴", isoCode: "AO" },
  { key: "Anguilla 🇦🇮", isoCode: "AI" },
  { key: "Antarctica 🇦🇶", isoCode: "AQ" },
  { key: "Antigua and Barbuda 🇦🇬", isoCode: "AG" },
  { key: "Argentina 🇦🇷", isoCode: "AR" },
  { key: "Armenia 🇦🇲", isoCode: "AM" },
  { key: "Aruba 🇦🇼", isoCode: "AW" },
  { key: "Australia 🇦🇺", isoCode: "AU" },
  { key: "Austria 🇦🇹", isoCode: "AT" },
  { key: "Azerbaijan 🇦🇿", isoCode: "AZ" },
  { key: "Bahamas 🇧🇸", isoCode: "BS" },
  { key: "Bahrain 🇧🇭", isoCode: "BH" },
  { key: "Bangladesh 🇧🇩", isoCode: "BD" },
  { key: "Barbados 🇧🇧", isoCode: "BB" },
  { key: "Belarus 🇧🇾", isoCode: "BY" },
  { key: "Belgium 🇧🇪", isoCode: "BE" },
  { key: "Belize 🇧🇿", isoCode: "BZ" },
  { key: "Benin 🇧🇯", isoCode: "BJ" },
  { key: "Bermuda 🇧🇲", isoCode: "BM" },
  { key: "Bhutan 🇧🇹", isoCode: "BT" },
  { key: "Bolivia 🇧🇴", isoCode: "BO" },
  { key: "Bonaire, Sint Eustatius and Saba 🇧🇶", isoCode: "BQ" },
  { key: "Bosnia and Herzegovina 🇧🇦", isoCode: "BA" },
  { key: "Botswana 🇧🇼", isoCode: "BW" },
  { key: "Bouvet Island 🇧🇻", isoCode: "BV" },
  { key: "Brazil 🇧🇷", isoCode: "BR" },
  { key: "British Indian Ocean Territory 🇮🇴", isoCode: "IO" },
  { key: "Brunei Darussalam 🇧🇳", isoCode: "BN" },
  { key: "Bulgaria 🇧🇬", isoCode: "BG" },
  { key: "Burkina Faso 🇧🇫", isoCode: "BF" },
  { key: "Burundi 🇧🇮", isoCode: "BI" },
  { key: "Cambodia 🇰🇭", isoCode: "KH" },
  { key: "Cameroon 🇨🇲", isoCode: "CM" },
  { key: "Canada 🇨🇦", isoCode: "CA" },
  { key: "Cape Verde 🇨🇻", isoCode: "CV" },
  { key: "Cayman Islands 🇰🇾", isoCode: "KY" },
  { key: "Central African Republic 🇨🇫", isoCode: "CF" },
  { key: "Chad 🇹🇩", isoCode: "TD" },
  { key: "Chile 🇨🇱", isoCode: "CL" },
  { key: "China 🇨🇳", isoCode: "CN" },
  { key: "Christmas Island 🇨🇽", isoCode: "CX" },
  { key: "Cocos (Keeling) Islands 🇨🇨", isoCode: "CC" },
  { key: "Colombia 🇨🇴", isoCode: "CO" },
  { key: "Comoros 🇰🇲", isoCode: "KM" },
  { key: "Congo 🇨🇬", isoCode: "CG" },
  { key: "Congo, the Democratic Republic of the 🇨🇩", isoCode: "CD" },
  { key: "Cook Islands 🇨🇰", isoCode: "CK" },
  { key: "Costa Rica 🇨🇷", isoCode: "CR" },
  { key: "Côte d'Ivoire 🇨🇮", isoCode: "CI" },
  { key: "Croatia 🇭🇷", isoCode: "HR" },
  { key: "Cuba 🇨🇺", isoCode: "CU" },
  { key: "Curaçao 🇨🇼", isoCode: "CW" },
  { key: "Cyprus 🇨🇾", isoCode: "CY" },
  { key: "Czech Republic 🇨🇿", isoCode: "CZ" },
  { key: "Denmark 🇩🇰", isoCode: "DK" },
  { key: "Djibouti 🇩🇯", isoCode: "DJ" },
  { key: "Dominica 🇩🇲", isoCode: "DM" },
  { key: "Dominican Republic 🇩🇴", isoCode: "DO" },
  { key: "Ecuador 🇪🇨", isoCode: "EC" },
  { key: "Egypt 🇪🇬", isoCode: "EG" },
  { key: "El Salvador 🇸🇻", isoCode: "SV" },
  { key: "Equatorial Guinea 🇬🇶", isoCode: "GQ" },
  { key: "Eritrea 🇪🇷", isoCode: "ER" },
  { key: "Estonia 🇪🇪", isoCode: "EE" },
  { key: "Ethiopia 🇪🇹", isoCode: "ET" },
  { key: "Falkland Islands (Malvinas) 🇫🇰", isoCode: "FK" },
  { key: "Faroe Islands 🇫🇴", isoCode: "FO" },
  { key: "Fiji 🇫🇯", isoCode: "FJ" },
  { key: "Finland 🇫🇮", isoCode: "FI" },
  { key: "France 🇫🇷", isoCode: "FR" },
  { key: "French Guiana 🇬🇫", isoCode: "GF" },
  { key: "French Polynesia 🇵🇫", isoCode: "PF" },
  { key: "French Southern Territories 🇹🇫", isoCode: "TF" },
  { key: "Gabon 🇬🇦", isoCode: "GA" },
  { key: "Gambia 🇬🇲", isoCode: "GM" },
  { key: "Georgia 🇬🇪", isoCode: "GE" },
  { key: "Germany 🇩🇪", isoCode: "DE" },
  { key: "Ghana 🇬🇭", isoCode: "GH" },
  { key: "Gibraltar 🇬🇮", isoCode: "GI" },
  { key: "Greece 🇬🇷", isoCode: "GR" },
  { key: "Greenland 🇬🇱", isoCode: "GL" },
  { key: "Grenada 🇬🇩", isoCode: "GD" },
  { key: "Guadeloupe 🇬🇵", isoCode: "GP" },
  { key: "Guam 🇬🇺", isoCode: "GU" },
  { key: "Guatemala 🇬🇹", isoCode: "GT" },
  { key: "Guernsey 🇬🇬", isoCode: "GG" },
  { key: "Guinea 🇬🇳", isoCode: "GN" },
  { key: "Guinea-Bissau 🇬🇼", isoCode: "GW" },
  { key: "Guyana 🇬🇾", isoCode: "GY" },
  { key: "Haiti 🇭🇹", isoCode: "HT" },
  { key: "Heard Island and McDonald Islands 🇭🇲", isoCode: "HM" },
  { key: "Holy See (Vatican City State) 🇻🇦", isoCode: "VA" },
  { key: "Honduras 🇭🇳", isoCode: "HN" },
  { key: "Hong Kong 🇭🇰", isoCode: "HK" },
  { key: "Hungary 🇭🇺", isoCode: "HU" },
  { key: "Iceland 🇮🇸", isoCode: "IS" },
  { key: "India 🇮🇳", isoCode: "IN" },
  { key: "Indonesia 🇮🇩", isoCode: "ID" },
  { key: "Iran, Islamic Republic of 🇮🇷", isoCode: "IR" },
  { key: "Iraq 🇮🇶", isoCode: "IQ" },
  { key: "Ireland 🇮🇪", isoCode: "IE" },
  { key: "Isle of Man 🇮🇲", isoCode: "IM" },
  { key: "Israel 🇮🇱", isoCode: "IL" },
  { key: "Italy 🇮🇹", isoCode: "IT" },
  { key: "Jamaica 🇯🇲", isoCode: "JM" },
  { key: "Japan 🇯🇵", isoCode: "JP" },
  { key: "Jersey 🇯🇪", isoCode: "JE" },
  { key: "Jordan 🇯🇴", isoCode: "JO" },
  { key: "Kazakhstan 🇰🇿", isoCode: "KZ" },
  { key: "Kenya 🇰🇪", isoCode: "KE" },
  { key: "Kiribati 🇰🇮", isoCode: "KI" },
  { key: "Korea, Democratic People's Republic of 🇰🇵", isoCode: "KP" },
  { key: "Korea, Republic of 🇰🇷", isoCode: "KR" },
  { key: "Kuwait 🇰🇼", isoCode: "KW" },
  { key: "Kyrgyzstan 🇰🇬", isoCode: "KG" },
  { key: "Lao People's Democratic Republic 🇱🇦", isoCode: "LA" },
  { key: "Latvia 🇱🇻", isoCode: "LV" },
  { key: "Lebanon 🇱🇧", isoCode: "LB" },
  { key: "Lesotho 🇱🇸", isoCode: "LS" },
  { key: "Liberia 🇱🇷", isoCode: "LR" },
  { key: "Libya 🇱🇾", isoCode: "LY" },
  { key: "Liechtenstein 🇱🇮", isoCode: "LI" },
  { key: "Lithuania 🇱🇹", isoCode: "LT" },
  { key: "Luxembourg 🇱🇺", isoCode: "LU" },
  { key: "Macao 🇲🇴", isoCode: "MO" },
  { key: "Macedonia, the Former Yugoslav Republic of 🇲🇰", isoCode: "MK" },
  { key: "Madagascar 🇲🇬", isoCode: "MG" },
  { key: "Malawi 🇲🇼", isoCode: "MW" },
  { key: "Malaysia 🇲🇾", isoCode: "MY" },
  { key: "Maldives 🇲🇻", isoCode: "MV" },
  { key: "Mali 🇲🇱", isoCode: "ML" },
  { key: "Malta 🇲🇹", isoCode: "MT" },
  { key: "Marshall Islands 🇲🇭", isoCode: "MH" },
  { key: "Martinique 🇲🇶", isoCode: "MQ" },
  { key: "Mauritania 🇲🇷", isoCode: "MR" },
  { key: "Mauritius 🇲🇺", isoCode: "MU" },
  { key: "Mayotte 🇾🇹", isoCode: "YT" },
  { key: "Mexico 🇲🇽", isoCode: "MX" },
  { key: "Micronesia, Federated States of 🇫🇲", isoCode: "FM" },
  { key: "Moldova, Republic of 🇲🇩", isoCode: "MD" },
  { key: "Monaco 🇲🇨", isoCode: "MC" },
  { key: "Mongolia 🇲🇳", isoCode: "MN" },
  { key: "Montenegro 🇲🇪", isoCode: "ME" },
  { key: "Montserrat 🇲🇸", isoCode: "MS" },
  { key: "Morocco 🇲🇦", isoCode: "MA" },
  { key: "Mozambique 🇲🇿", isoCode: "MZ" },
  { key: "Myanmar 🇲🇲", isoCode: "MM" },
  { key: "Namibia 🇳🇦", isoCode: "NA" },
  { key: "Nauru 🇳🇷", isoCode: "NR" },
  { key: "Nepal 🇳🇵", isoCode: "NP" },
  { key: "Netherlands 🇳🇱", isoCode: "NL" },
  { key: "New Caledonia 🇳🇨", isoCode: "NC" },
  { key: "New Zealand 🇳🇿", isoCode: "NZ" },
  { key: "Nicaragua 🇳🇮", isoCode: "NI" },
  { key: "Niger 🇳🇪", isoCode: "NE" },
  { key: "Nigeria 🇳🇬", isoCode: "NG" },
  { key: "Niue 🇳🇺", isoCode: "NU" },
  { key: "Norfolk Island 🇳🇫", isoCode: "NF" },
  { key: "Northern Mariana Islands 🇲🇵", isoCode: "MP" },
  { key: "Norway 🇳🇴", isoCode: "NO" },
  { key: "Oman 🇴🇲", isoCode: "OM" },
  { key: "Pakistan 🇵🇰", isoCode: "PK" },
  { key: "Palau 🇵🇼", isoCode: "PW" },
  { key: "Palestine, State of 🇵🇸", isoCode: "PS" },
  { key: "Panama 🇵🇦", isoCode: "PA" },
  { key: "Papua New Guinea 🇵🇬", isoCode: "PG" },
  { key: "Paraguay 🇵🇾", isoCode: "PY" },
  { key: "Peru 🇵🇪", isoCode: "PE" },
  { key: "Philippines 🇵🇭", isoCode: "PH" },
  { key: "Pitcairn 🇵🇳", isoCode: "PN" },
  { key: "Poland 🇵🇱", isoCode: "PL" },
  { key: "Portugal 🇵🇹", isoCode: "PT" },
  { key: "Puerto Rico 🇵🇷", isoCode: "PR" },
  { key: "Qatar 🇶🇦", isoCode: "QA" },
  { key: "Réunion 🇷🇪", isoCode: "RE" },
  { key: "Romania 🇷🇴", isoCode: "RO" },
  { key: "Russian Federation 🇷🇺", isoCode: "RU" },
  { key: "Rwanda 🇷🇼", isoCode: "RW" },
  { key: "Saint Barthélemy 🇧🇱", isoCode: "BL" },
  { key: "Saint Helena, Ascension and Tristan da Cunha 🇸🇭", isoCode: "SH" },
  { key: "Saint Kitts and Nevis 🇰🇳", isoCode: "KN" },
  { key: "Saint Lucia 🇱🇨", isoCode: "LC" },
  { key: "Saint Martin (French part) 🇲🇫", isoCode: "MF" },
  { key: "Saint Pierre and Miquelon 🇵🇲", isoCode: "PM" },
  { key: "Saint Vincent and the Grenadines 🇻🇨", isoCode: "VC" },
  { key: "Samoa 🇼🇸", isoCode: "WS" },
  { key: "San Marino 🇸🇲", isoCode: "SM" },
  { key: "Sao Tome and Principe 🇸🇹", isoCode: "ST" },
  { key: "Saudi Arabia 🇸🇦", isoCode: "SA" },
  { key: "Senegal 🇸🇳", isoCode: "SN" },
  { key: "Serbia 🇷🇸", isoCode: "RS" },
  { key: "Seychelles 🇸🇨", isoCode: "SC" },
  { key: "Sierra Leone 🇸🇱", isoCode: "SL" },
  { key: "Singapore 🇸🇬", isoCode: "SG" },
  { key: "Sint Maarten (Dutch part) 🇸🇽", isoCode: "SX" },
  { key: "Slovakia 🇸🇰", isoCode: "SK" },
  { key: "Slovenia 🇸🇮", isoCode: "SI" },
  { key: "Solomon Islands 🇸🇧", isoCode: "SB" },
  { key: "Somalia 🇸🇴", isoCode: "SO" },
  { key: "South Africa 🇿🇦", isoCode: "ZA" },
  { key: "South Georgia and the South Sandwich Islands 🇬🇸", isoCode: "GS" },
  { key: "South Sudan 🇸🇸", isoCode: "SS" },
  { key: "Spain 🇪🇸", isoCode: "ES" },
  { key: "Sri Lanka 🇱🇰", isoCode: "LK" },
  { key: "Sudan 🇸🇩", isoCode: "SD" },
  { key: "Suriname 🇸🇷", isoCode: "SR" },
  { key: "Svalbard and Jan Mayen 🇸🇯", isoCode: "SJ" },
  { key: "Eswatini 🇸🇿", isoCode: "SZ" },
  { key: "Sweden 🇸🇪", isoCode: "SE" },
  { key: "Switzerland 🇨🇭", isoCode: "CH" },
  { key: "Syrian Arab Republic 🇸🇾", isoCode: "SY" },
  { key: "Taiwan, Province of China 🇹🇼", isoCode: "TW" },
  { key: "Tajikistan 🇹🇯", isoCode: "TJ" },
  { key: "Tanzania, United Republic of 🇹🇿", isoCode: "TZ" },
  { key: "Thailand 🇹🇭", isoCode: "TH" },
  { key: "Timor-Leste 🇹🇱", isoCode: "TL" },
  { key: "Togo 🇹🇬", isoCode: "TG" },
  { key: "Tokelau 🇹🇰", isoCode: "TK" },
  { key: "Tonga 🇹🇴", isoCode: "TO" },
  { key: "Trinidad and Tobago 🇹🇹", isoCode: "TT" },
  { key: "Tunisia 🇹🇳", isoCode: "TN" },
  { key: "Turkey 🇹🇷", isoCode: "TR" },
  { key: "Turkmenistan 🇹🇲", isoCode: "TM" },
  { key: "Turks and Caicos Islands 🇹🇨", isoCode: "TC" },
  { key: "Tuvalu 🇹🇻", isoCode: "TV" },
  { key: "Uganda 🇺🇬", isoCode: "UG" },
  { key: "Ukraine 🇺🇦", isoCode: "UA" },
  { key: "United Arab Emirates 🇦🇪", isoCode: "AE" },
  { key: "United Kingdom 🇬🇧", isoCode: "GB" },
  { key: "United States 🇺🇸", isoCode: "US" },
  { key: "United States Minor Outlying Islands 🇺🇲", isoCode: "UM" },
  { key: "Uruguay 🇺🇾", isoCode: "UY" },
  { key: "Uzbekistan 🇺🇿", isoCode: "UZ" },
  { key: "Vanuatu 🇻🇺", isoCode: "VU" },
  { key: "Venezuela, Bolivarian Republic of 🇻🇪", isoCode: "VE" },
  { key: "Viet Nam 🇻🇳", isoCode: "VN" },
  { key: "Virgin Islands, British 🇻🇬", isoCode: "VG" },
  { key: "Virgin Islands, U.S. 🇻🇮", isoCode: "VI" },
  { key: "Wallis and Futuna 🇼🇫", isoCode: "WF" },
  { key: "Western Sahara 🇪🇭", isoCode: "EH" },
  { key: "Yemen 🇾🇪", isoCode: "YE" },
  { key: "Zambia 🇿🇲", isoCode: "ZM" },
  { key: "Zimbabwe 🇿🇼", isoCode: "ZW" },
]

export const aviationCompliments = [
  "Smooth as butter landing!",
  "Captain of the skies!",
  "Sky wizard extraordinaire!",
  "Turbulence? What turbulence?",
  "Flying like a boss!",
  "Cleared for awesome!",
  "Altitude master supreme!",
  "Sky dancing legend!",
  "Cloud surfing champion!",
  "Aviation ace pilot!",
  "Runway ruler royalty!",
  "Cockpit commander king!",
  "Flight path perfectionist!",
  "Airspace artist genius!",
  "Wind whisperer wizard!",
  "Throttle control master!",
  "Navigation ninja skills!",
  "Crosswind crushing hero!",
  "Fuel efficiency guru!",
  "Radio communication star!",
  "Weather dodging expert!",
  "Formation flying ace!",
  "Instrument reading legend!",
  "Approach angle artist!",
  "Departure timing genius!",
  "Pattern flying poet!",
  "Tower talking champion!",
  "Checklist checking master!",
  "Emergency handling hero!",
  "Precision flying machine!",
  "Altitude holding wizard!",
  "Speed control surgeon!",
  "Banking angle beauty!",
  "Descent rate dancer!",
  "Climb gradient genius!",
  "Heading holding hero!",
  "Frequency finding wizard!",
  "Squawk code specialist!",
  "Vector following virtuoso!",
  "Clearance copying champion!",
  "Traffic spotting eagle!",
  "Weather reading sage!",
  "Chart reading champion!",
  "GPS programming pro!",
  "Autopilot adjusting ace!",
  "Flap setting maestro!",
  "Gear operating genius!",
  "Trim tab tactician!",
  "Rudder work rockstar!",
  "Aileron artist supreme!",
  "Elevator expert elite!",
  "Propeller pitch perfectionist!",
  "Mixture management master!",
  "Cowl flap controller!",
  "Fuel pump professional!",
  "Magneto switching specialist!",
  "Carb heat handler!",
  "Oil pressure observer!",
  "Engine temperature tracker!",
  "Electrical system expert!",
  "Hydraulic pressure hero!",
  "Vacuum system virtuoso!",
  "Pitot tube protector!",
  "Static port specialist!",
  "Altimeter adjusting ace!",
  "Compass calibration king!",
  "VOR navigation ninja!",
  "ILS approach artist!",
  "GPS guidance guru!",
  "DME distance detective!",
  "ADF bearing boss!",
  "Transponder code genius!",
  "Comm radio rockstar!",
  "Ground control groupie!",
  "Tower frequency finder!",
  "Approach control ace!",
  "Departure procedure pro!",
  "En route expert elite!",
  "Class airspace ambassador!",
  "NOTAM knowledge ninja!",
  "TFR tracking tactician!",
  "Weather briefing boss!",
  "Flight planning phenom!",
  "Weight balance wizard!",
  "Performance chart champion!",
  "Density altitude detective!",
  "Wind triangle warrior!",
  "Cross country crusader!",
  "Pattern work perfectionist!",
  "Touch and go guru!",
  "Short field specialist!",
  "Soft field sensation!",
  "Emergency landing legend!",
  "Go around genius!",
  "Missed approach master!",
  "Holding pattern hero!",
  "Steep turn tactician!",
  "Stall recovery rockstar!",
  "Spin awareness specialist!",
  "Ground reference guru!",
  "Hood time hero!",
  "Night flying ninja!",
  "Cross country commander!",
  "Solo flight superstar!",
  "Checkride champion!",
  "Blue sky explorer!",
  "Cloud hopping hero!",
];
export const alternator = [
  "🤖", "👽", "👾", "👻", "💀", "🤡", "🤠", "🤖", "👽", "💩",
  "🤮", "🤢", "🤧", "🤒", "🤕", "🤑", "🤓", "🤔", "🤕", "👀", 
  "🥶", "🌭", "🍔", "🐸", "👹", "😹", "🤯", "😮‍💨", "😘", "⛽️", 
  "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯",
  "🦁", "🐮", "🐷", "🐸", "🐵", "🐔", "🐧", "🐦", "🐤", "🦆",
  "🦅", "🦉", "🦇", "🐺", "🐗", "🐴", "🦄", "🐝", "🪱", "🐛",
  "🦋", "🐌", "🐞", "🐜", "🦂", "🦟", "🦗", "🕷️", "🕸️", "🐢",
  "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦞", "🦀", "🐡",
  "🐠", "🐟", "🐬", "🐳", "🐋", "🦈", "🐊", "🐅", "🐆", "🦓",
  "🍏", "🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐",
  "🥝", "🍍", "🥭", "🥥", "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️",
  "🫑", "🥒", "🥬", "🥦", "🧄", "🧅", "🍄", "🥜", "🌰", "🍞",
  "🥐", "🥖", "🫓", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖", "🍗",
  "🥩", "🥓", "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯", "🫔",
  "🥙", "🧆", "🥘", "🍲", "🍝", "🍜", "🍛", "🍣", "🍱", "🥟",
  "🦪", "🍤", "🍚", "🍘", "🍥", "🥠", "🥮", "🍢", "🍡", "🍧",
  "🍨", "🍦", "🥧", "🍰", "🎂", "🧁", "🍮", "🍭", "🍬", "🍫",
  "🍿", "🍩", "🍪", "🥛", "🍼", "☕", "🫖", "🍵", "🍶", "🍺",
  "🍻", "🥂", "🍷", "🥃", "🍸", "🍹", "🧃", "🧉", "🧊",
  "💻", "🖥️", "📱", "📲", "⌚", "⌨️", "🖱️", "🖲️", "🕹️", "💽",
  "💾", "💿", "📀", "📼", "📷", "📸", "📹", "🎥", "📽️", "🎞️",
  "📞", "☎️", "📟", "📠", "📺", "📻", "🎙️", "🎚️", "🎛️", "🧭",
  "⏰", "⏱️", "⏲️", "🕰️", "🌡️", "🧱", "🔋", "🔌", "💡", "🔦",
  "🕯️", "🧯", "🛢️", "💸", "💵", "💴", "💶", "💷", "💳", "🧾",
  "✈️","💺", "🛣️"
  ];

  export const customUserImages = [
    {
      username: "rulizalhafizh",
      image: `https://images.weserv.nl/?url=${encodeURIComponent("https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/rulizalhafizh/288/1061097_2.png")}&w=64&h=64&fit=cover&mask=circle`
    },
    {
      username: "Veloist",
      image: `https://images.weserv.nl/?url=${encodeURIComponent("https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/veloist/288/1509072_2.png")}&w=64&h=64&fit=cover&mask=circle`
    }
  ]
    