export const aircraftImages = [
    { key: "a220", image: "a220.png" },
    { key: "a319", image: "a319.png" },
    { key: "a320", image: "a319.png" },
    { key: "a321", image: "a321.png" },
    { key: "a330", image: "a330.png" },
    { key: "a330f", image: "a330f.png" },
    { key: "a330neo", image: "a330neo.png" },
    { key: "a340", image: "a340.png" },
    { key: "a350", image: "a350.png" },
    { key: "a380", image: "a380.png" },
    { key: "e175", image: "e175.png" },
    { key: "e190", image: "e190.png" },
    { key: "tbm-930", image: "tbm930.png" },
    { key: "boeing 717", image: "b717.png" },
    { key: "boeing 737-700", image: "b737-700.png" },
    { key: "boeing 737-800", image: "b737-800.png" },
    { key: "boeing 737-900", image: "b737-900.png" },
    { key: "boeing 737-8 max", image: "b737-8max.png" },
    { key: "boeing 747-200", image: "b747-200.png" },
    { key: "boeing 747-400", image: "b747-400.png" },
    { key: "boeing 747-8", image: "b747-8.png" },
    { key: "boeing 757-200", image: "b757.png" },
    { key: "boeing 767", image: "b767.png" },
    { key: "boeing 777-200ER", image: "b777-200.png" },
    { key: "boeing 777-200LR", image: "b777-200.png" },
    { key: "boeing 777-300ER", image: "b777-300.png" },
    { key: "boeing 787-8", image: "b787-8.png" },
    { key: "boeing 787-9", image: "b787-9.png" },
    { key: "boeing 787-10", image: "b787-10.png" },
    { key: "md-11f", image: "md11f.png" },
];

export const emojiCharacterRandomizer = [
  "🤫",
  "🙃",
  "🤔",
  "🤨",
  "🤯",
  "🤠",
  "😲",
  "🙂‍↕️",
  "🙂‍↔️",
  "🥳",
];

export const isoCountryCodes = [
  { key: "Afghanistan 🇦🇫", isoCode: "AF" },
  { key: "Åland Islands 🇦🇽", isoCode: "AX" },
  { key: "Albania 🇦🇱", isoCode: "AL" },
  { key: "Algeria 🇩🇿", isoCode: "DZ" },
  { key: "American Samoa 🇦🇸", isoCode: "AS" },
  { key: "Andorra 🇦🇩", isoCode: "AD" },
  { key: "Angola 🇦🇴", isoCode: "AO" },
  { key: "Anguilla 🇦🇮", isoCode: "AI" },
  { key: "Antarctica 🇦🇶", isoCode: "AQ" },
  { key: "Antigua and Barbuda 🇦🇬", isoCode: "AG" },
  { key: "Argentina 🇦🇷", isoCode: "AR" },
  { key: "Armenia 🇦🇲", isoCode: "AM" },
  { key: "Aruba 🇦🇼", isoCode: "AW" },
  { key: "Australia 🇦🇺", isoCode: "AU" },
  { key: "Austria 🇦🇹", isoCode: "AT" },
  { key: "Azerbaijan 🇦🇿", isoCode: "AZ" },
  { key: "Bahamas 🇧🇸", isoCode: "BS" },
  { key: "Bahrain 🇧🇭", isoCode: "BH" },
  { key: "Bangladesh 🇧🇩", isoCode: "BD" },
  { key: "Barbados 🇧🇧", isoCode: "BB" },
  { key: "Belarus 🇧🇾", isoCode: "BY" },
  { key: "Belgium 🇧🇪", isoCode: "BE" },
  { key: "Belize 🇧🇿", isoCode: "BZ" },
  { key: "Benin 🇧🇯", isoCode: "BJ" },
  { key: "Bermuda 🇧🇲", isoCode: "BM" },
  { key: "Bhutan 🇧🇹", isoCode: "BT" },
  { key: "Bolivia 🇧🇴", isoCode: "BO" },
  { key: "Bonaire, Sint Eustatius and Saba 🇧🇶", isoCode: "BQ" },
  { key: "Bosnia and Herzegovina 🇧🇦", isoCode: "BA" },
  { key: "Botswana 🇧🇼", isoCode: "BW" },
  { key: "Bouvet Island 🇧🇻", isoCode: "BV" },
  { key: "Brazil 🇧🇷", isoCode: "BR" },
  { key: "British Indian Ocean Territory 🇮🇴", isoCode: "IO" },
  { key: "Brunei Darussalam 🇧🇳", isoCode: "BN" },
  { key: "Bulgaria 🇧🇬", isoCode: "BG" },
  { key: "Burkina Faso 🇧🇫", isoCode: "BF" },
  { key: "Burundi 🇧🇮", isoCode: "BI" },
  { key: "Cambodia 🇰🇭", isoCode: "KH" },
  { key: "Cameroon 🇨🇲", isoCode: "CM" },
  { key: "Canada 🇨🇦", isoCode: "CA" },
  { key: "Cape Verde 🇨🇻", isoCode: "CV" },
  { key: "Cayman Islands 🇰🇾", isoCode: "KY" },
  { key: "Central African Republic 🇨🇫", isoCode: "CF" },
  { key: "Chad 🇹🇩", isoCode: "TD" },
  { key: "Chile 🇨🇱", isoCode: "CL" },
  { key: "China 🇨🇳", isoCode: "CN" },
  { key: "Christmas Island 🇨🇽", isoCode: "CX" },
  { key: "Cocos (Keeling) Islands 🇨🇨", isoCode: "CC" },
  { key: "Colombia 🇨🇴", isoCode: "CO" },
  { key: "Comoros 🇰🇲", isoCode: "KM" },
  { key: "Congo 🇨🇬", isoCode: "CG" },
  { key: "Congo, the Democratic Republic of the 🇨🇩", isoCode: "CD" },
  { key: "Cook Islands 🇨🇰", isoCode: "CK" },
  { key: "Costa Rica 🇨🇷", isoCode: "CR" },
  { key: "Côte d'Ivoire 🇨🇮", isoCode: "CI" },
  { key: "Croatia 🇭🇷", isoCode: "HR" },
  { key: "Cuba 🇨🇺", isoCode: "CU" },
  { key: "Curaçao 🇨🇼", isoCode: "CW" },
  { key: "Cyprus 🇨🇾", isoCode: "CY" },
  { key: "Czech Republic 🇨🇿", isoCode: "CZ" },
  { key: "Denmark 🇩🇰", isoCode: "DK" },
  { key: "Djibouti 🇩🇯", isoCode: "DJ" },
  { key: "Dominica 🇩🇲", isoCode: "DM" },
  { key: "Dominican Republic 🇩🇴", isoCode: "DO" },
  { key: "Ecuador 🇪🇨", isoCode: "EC" },
  { key: "Egypt 🇪🇬", isoCode: "EG" },
  { key: "El Salvador 🇸🇻", isoCode: "SV" },
  { key: "Equatorial Guinea 🇬🇶", isoCode: "GQ" },
  { key: "Eritrea 🇪🇷", isoCode: "ER" },
  { key: "Estonia 🇪🇪", isoCode: "EE" },
  { key: "Ethiopia 🇪🇹", isoCode: "ET" },
  { key: "Falkland Islands (Malvinas) 🇫🇰", isoCode: "FK" },
  { key: "Faroe Islands 🇫🇴", isoCode: "FO" },
  { key: "Fiji 🇫🇯", isoCode: "FJ" },
  { key: "Finland 🇫🇮", isoCode: "FI" },
  { key: "France 🇫🇷", isoCode: "FR" },
  { key: "French Guiana 🇬🇫", isoCode: "GF" },
  { key: "French Polynesia 🇵🇫", isoCode: "PF" },
  { key: "French Southern Territories 🇹🇫", isoCode: "TF" },
  { key: "Gabon 🇬🇦", isoCode: "GA" },
  { key: "Gambia 🇬🇲", isoCode: "GM" },
  { key: "Georgia 🇬🇪", isoCode: "GE" },
  { key: "Germany 🇩🇪", isoCode: "DE" },
  { key: "Ghana 🇬🇭", isoCode: "GH" },
  { key: "Gibraltar 🇬🇮", isoCode: "GI" },
  { key: "Greece 🇬🇷", isoCode: "GR" },
  { key: "Greenland 🇬🇱", isoCode: "GL" },
  { key: "Grenada 🇬🇩", isoCode: "GD" },
  { key: "Guadeloupe 🇬🇵", isoCode: "GP" },
  { key: "Guam 🇬🇺", isoCode: "GU" },
  { key: "Guatemala 🇬🇹", isoCode: "GT" },
  { key: "Guernsey 🇬🇬", isoCode: "GG" },
  { key: "Guinea 🇬🇳", isoCode: "GN" },
  { key: "Guinea-Bissau 🇬🇼", isoCode: "GW" },
  { key: "Guyana 🇬🇾", isoCode: "GY" },
  { key: "Haiti 🇭🇹", isoCode: "HT" },
  { key: "Heard Island and McDonald Islands 🇭🇲", isoCode: "HM" },
  { key: "Holy See (Vatican City State) 🇻🇦", isoCode: "VA" },
  { key: "Honduras 🇭🇳", isoCode: "HN" },
  { key: "Hong Kong 🇭🇰", isoCode: "HK" },
  { key: "Hungary 🇭🇺", isoCode: "HU" },
  { key: "Iceland 🇮🇸", isoCode: "IS" },
  { key: "India 🇮🇳", isoCode: "IN" },
  { key: "Indonesia 🇮🇩", isoCode: "ID" },
  { key: "Iran, Islamic Republic of 🇮🇷", isoCode: "IR" },
  { key: "Iraq 🇮🇶", isoCode: "IQ" },
  { key: "Ireland 🇮🇪", isoCode: "IE" },
  { key: "Isle of Man 🇮🇲", isoCode: "IM" },
  { key: "Israel 🇮🇱", isoCode: "IL" },
  { key: "Italy 🇮🇹", isoCode: "IT" },
  { key: "Jamaica 🇯🇲", isoCode: "JM" },
  { key: "Japan 🇯🇵", isoCode: "JP" },
  { key: "Jersey 🇯🇪", isoCode: "JE" },
  { key: "Jordan 🇯🇴", isoCode: "JO" },
  { key: "Kazakhstan 🇰🇿", isoCode: "KZ" },
  { key: "Kenya 🇰🇪", isoCode: "KE" },
  { key: "Kiribati 🇰🇮", isoCode: "KI" },
  { key: "Korea, Democratic People's Republic of 🇰🇵", isoCode: "KP" },
  { key: "Korea, Republic of 🇰🇷", isoCode: "KR" },
  { key: "Kuwait 🇰🇼", isoCode: "KW" },
  { key: "Kyrgyzstan 🇰🇬", isoCode: "KG" },
  { key: "Lao People's Democratic Republic 🇱🇦", isoCode: "LA" },
  { key: "Latvia 🇱🇻", isoCode: "LV" },
  { key: "Lebanon 🇱🇧", isoCode: "LB" },
  { key: "Lesotho 🇱🇸", isoCode: "LS" },
  { key: "Liberia 🇱🇷", isoCode: "LR" },
  { key: "Libya 🇱🇾", isoCode: "LY" },
  { key: "Liechtenstein 🇱🇮", isoCode: "LI" },
  { key: "Lithuania 🇱🇹", isoCode: "LT" },
  { key: "Luxembourg 🇱🇺", isoCode: "LU" },
  { key: "Macao 🇲🇴", isoCode: "MO" },
  { key: "Macedonia, the Former Yugoslav Republic of 🇲🇰", isoCode: "MK" },
  { key: "Madagascar 🇲🇬", isoCode: "MG" },
  { key: "Malawi 🇲🇼", isoCode: "MW" },
  { key: "Malaysia 🇲🇾", isoCode: "MY" },
  { key: "Maldives 🇲🇻", isoCode: "MV" },
  { key: "Mali 🇲🇱", isoCode: "ML" },
  { key: "Malta 🇲🇹", isoCode: "MT" },
  { key: "Marshall Islands 🇲🇭", isoCode: "MH" },
  { key: "Martinique 🇲🇶", isoCode: "MQ" },
  { key: "Mauritania 🇲🇷", isoCode: "MR" },
  { key: "Mauritius 🇲🇺", isoCode: "MU" },
  { key: "Mayotte 🇾🇹", isoCode: "YT" },
  { key: "Mexico 🇲🇽", isoCode: "MX" },
  { key: "Micronesia, Federated States of 🇫🇲", isoCode: "FM" },
  { key: "Moldova, Republic of 🇲🇩", isoCode: "MD" },
  { key: "Monaco 🇲🇨", isoCode: "MC" },
  { key: "Mongolia 🇲🇳", isoCode: "MN" },
  { key: "Montenegro 🇲🇪", isoCode: "ME" },
  { key: "Montserrat 🇲🇸", isoCode: "MS" },
  { key: "Morocco 🇲🇦", isoCode: "MA" },
  { key: "Mozambique 🇲🇿", isoCode: "MZ" },
  { key: "Myanmar 🇲🇲", isoCode: "MM" },
  { key: "Namibia 🇳🇦", isoCode: "NA" },
  { key: "Nauru 🇳🇷", isoCode: "NR" },
  { key: "Nepal 🇳🇵", isoCode: "NP" },
  { key: "Netherlands 🇳🇱", isoCode: "NL" },
  { key: "New Caledonia 🇳🇨", isoCode: "NC" },
  { key: "New Zealand 🇳🇿", isoCode: "NZ" },
  { key: "Nicaragua 🇳🇮", isoCode: "NI" },
  { key: "Niger 🇳🇪", isoCode: "NE" },
  { key: "Nigeria 🇳🇬", isoCode: "NG" },
  { key: "Niue 🇳🇺", isoCode: "NU" },
  { key: "Norfolk Island 🇳🇫", isoCode: "NF" },
  { key: "Northern Mariana Islands 🇲🇵", isoCode: "MP" },
  { key: "Norway 🇳🇴", isoCode: "NO" },
  { key: "Oman 🇴🇲", isoCode: "OM" },
  { key: "Pakistan 🇵🇰", isoCode: "PK" },
  { key: "Palau 🇵🇼", isoCode: "PW" },
  { key: "Palestine, State of 🇵🇸", isoCode: "PS" },
  { key: "Panama 🇵🇦", isoCode: "PA" },
  { key: "Papua New Guinea 🇵🇬", isoCode: "PG" },
  { key: "Paraguay 🇵🇾", isoCode: "PY" },
  { key: "Peru 🇵🇪", isoCode: "PE" },
  { key: "Philippines 🇵🇭", isoCode: "PH" },
  { key: "Pitcairn 🇵🇳", isoCode: "PN" },
  { key: "Poland 🇵🇱", isoCode: "PL" },
  { key: "Portugal 🇵🇹", isoCode: "PT" },
  { key: "Puerto Rico 🇵🇷", isoCode: "PR" },
  { key: "Qatar 🇶🇦", isoCode: "QA" },
  { key: "Réunion 🇷🇪", isoCode: "RE" },
  { key: "Romania 🇷🇴", isoCode: "RO" },
  { key: "Russian Federation 🇷🇺", isoCode: "RU" },
  { key: "Rwanda 🇷🇼", isoCode: "RW" },
  { key: "Saint Barthélemy 🇧🇱", isoCode: "BL" },
  { key: "Saint Helena, Ascension and Tristan da Cunha 🇸🇭", isoCode: "SH" },
  { key: "Saint Kitts and Nevis 🇰🇳", isoCode: "KN" },
  { key: "Saint Lucia 🇱🇨", isoCode: "LC" },
  { key: "Saint Martin (French part) 🇲🇫", isoCode: "MF" },
  { key: "Saint Pierre and Miquelon 🇵🇲", isoCode: "PM" },
  { key: "Saint Vincent and the Grenadines 🇻🇨", isoCode: "VC" },
  { key: "Samoa 🇼🇸", isoCode: "WS" },
  { key: "San Marino 🇸🇲", isoCode: "SM" },
  { key: "Sao Tome and Principe 🇸🇹", isoCode: "ST" },
  { key: "Saudi Arabia 🇸🇦", isoCode: "SA" },
  { key: "Senegal 🇸🇳", isoCode: "SN" },
  { key: "Serbia 🇷🇸", isoCode: "RS" },
  { key: "Seychelles 🇸🇨", isoCode: "SC" },
  { key: "Sierra Leone 🇸🇱", isoCode: "SL" },
  { key: "Singapore 🇸🇬", isoCode: "SG" },
  { key: "Sint Maarten (Dutch part) 🇸🇽", isoCode: "SX" },
  { key: "Slovakia 🇸🇰", isoCode: "SK" },
  { key: "Slovenia 🇸🇮", isoCode: "SI" },
  { key: "Solomon Islands 🇸🇧", isoCode: "SB" },
  { key: "Somalia 🇸🇴", isoCode: "SO" },
  { key: "South Africa 🇿🇦", isoCode: "ZA" },
  { key: "South Georgia and the South Sandwich Islands 🇬🇸", isoCode: "GS" },
  { key: "South Sudan 🇸🇸", isoCode: "SS" },
  { key: "Spain 🇪🇸", isoCode: "ES" },
  { key: "Sri Lanka 🇱🇰", isoCode: "LK" },
  { key: "Sudan 🇸🇩", isoCode: "SD" },
  { key: "Suriname 🇸🇷", isoCode: "SR" },
  { key: "Svalbard and Jan Mayen 🇸🇯", isoCode: "SJ" },
  { key: "Eswatini 🇸🇿", isoCode: "SZ" },
  { key: "Sweden 🇸🇪", isoCode: "SE" },
  { key: "Switzerland 🇨🇭", isoCode: "CH" },
  { key: "Syrian Arab Republic 🇸🇾", isoCode: "SY" },
  { key: "Taiwan, Province of China 🇹🇼", isoCode: "TW" },
  { key: "Tajikistan 🇹🇯", isoCode: "TJ" },
  { key: "Tanzania, United Republic of 🇹🇿", isoCode: "TZ" },
  { key: "Thailand 🇹🇭", isoCode: "TH" },
  { key: "Timor-Leste 🇹🇱", isoCode: "TL" },
  { key: "Togo 🇹🇬", isoCode: "TG" },
  { key: "Tokelau 🇹🇰", isoCode: "TK" },
  { key: "Tonga 🇹🇴", isoCode: "TO" },
  { key: "Trinidad and Tobago 🇹🇹", isoCode: "TT" },
  { key: "Tunisia 🇹🇳", isoCode: "TN" },
  { key: "Turkey 🇹🇷", isoCode: "TR" },
  { key: "Turkmenistan 🇹🇲", isoCode: "TM" },
  { key: "Turks and Caicos Islands 🇹🇨", isoCode: "TC" },
  { key: "Tuvalu 🇹🇻", isoCode: "TV" },
  { key: "Uganda 🇺🇬", isoCode: "UG" },
  { key: "Ukraine 🇺🇦", isoCode: "UA" },
  { key: "United Arab Emirates 🇦🇪", isoCode: "AE" },
  { key: "United Kingdom 🇬🇧", isoCode: "GB" },
  { key: "United States 🇺🇸", isoCode: "US" },
  { key: "United States Minor Outlying Islands 🇺🇲", isoCode: "UM" },
  { key: "Uruguay 🇺🇾", isoCode: "UY" },
  { key: "Uzbekistan 🇺🇿", isoCode: "UZ" },
  { key: "Vanuatu 🇻🇺", isoCode: "VU" },
  { key: "Venezuela, Bolivarian Republic of 🇻🇪", isoCode: "VE" },
  { key: "Viet Nam 🇻🇳", isoCode: "VN" },
  { key: "Virgin Islands, British 🇻🇬", isoCode: "VG" },
  { key: "Virgin Islands, U.S. 🇻🇮", isoCode: "VI" },
  { key: "Wallis and Futuna 🇼🇫", isoCode: "WF" },
  { key: "Western Sahara 🇪🇭", isoCode: "EH" },
  { key: "Yemen 🇾🇪", isoCode: "YE" },
  { key: "Zambia 🇿🇲", isoCode: "ZM" },
  { key: "Zimbabwe 🇿🇼", isoCode: "ZW" },
];

export const aviationCompliments = [
  "Smooth as butter landing!",
  "Infinite Flight legend in the making!",
  "MSFS scenery downloading champion!",
  "X-Plane physics defying wizard!",
  "Captain of the skies!",
  "Sky wizard extraordinaire!",
  "Turbulence? What turbulence?",
  "Flying like a boss!",
  "Cleared for awesome!",
  "Altitude master supreme!",
  "Sky dancing legend!",
  "Cloud surfing champion!",
  "Master of respawning at checkpoints!",
  "Professional NPC conversation skipper!",
  "Expert inventory Tetris organizer!",
  "Champion of button mashing techniques!",
  "Elite cutscene sitting specialist!",
  "Professional loading screen starer!",
  "Master of tutorial level repeater!",
  "Expert save file corruption survivor!",
  "Champion of lag compensation warrior!",
  "Professional Wi-Fi disconnection handler!",
  "Master of controller battery depleter!",
  "Elite screen brightness adjuster!",
  "Champion of volume slider perfectionist!",
  "Professional graphics settings optimizer!",
  "Expert keybinding customization guru!",
  "Master of achievement notification reader!",
  "Elite trophy screenshot taker!",
  "Champion of leaderboard position checker!",
  "Professional DLC content purchaser!",
  "Expert microtransaction resistor!",
  "Master of loot box opening ceremony!",
  "Elite skin collection curator!",
  "Champion of cosmetic item hoarder!",
  "Professional character creation artist!",
  "Expert gender swap experimenter!",
  "Master of name generation randomizer!",
  "Elite backstory imagination writer!",
  "Champion of max level achiever!",
  "Professional experience point farmer!",
  "Expert skill tree navigator!",
  "Master of attribute point allocator!",
  "Elite perk selection strategist!",
  "Champion of build optimization calculator!",
  "Professional meta game researcher!",
  "Expert tier list memorizer!",
  "Master of patch note reader!",
  "Descent rate dancer!",
  "Climb gradient genius!",
  "Heading holding hero!",
  "Frequency finding wizard!",
  "Squawk code specialist!",
  "Vector following virtuoso!",
  "Clearance copying champion!",
  "Traffic spotting eagle!",
  "Weather reading sage!",
  "Chart reading champion!",
  "GPS programming pro!",
  "Autopilot adjusting ace!",
  "Flap setting maestro!",
  "Gear operating genius!",
  "Trim tab tactician!",
  "Rudder work rockstar!",
  "Aileron artist supreme!",
  "More legendary than a Minecraft dirt block!",
  "Has that Pac-Man dot eating energy!",
  "Smoother than Mario's mustache wax!",
  "More powerful than Luigi's green overalls!",
  "Cooler than Sonic's blue shoes!",
  "Has that Tetris block stacking precision!",
  "More epic than a Zelda rupee find!",
  "Stronger than a Pokémon using Splash!",
  "Has that Among Us task completing dedication!",
  "More reliable than Skyrim's loading screens!",
  "Faster than a Fortnite default skin dancer!",
  "Has that Minecraft Steve punching tree power!",
  "More organized than a Sims house builder!",
  "Cooler than a Call of Duty quickscoper!",
  "Has that GTA traffic light respecting energy!",
  "More patient than a Farmville crop waiter!",
  "Stronger than a Candy Crush level 1 player!",
  "Has that Angry Birds trajectory calculating skill!",
  "More dedicated than a World of Warcraft fisherman!",
  "Cooler than a Roblox character with Robux!",
  "Has that Fall Guys bean jumping technique!",
  "More precise than a Guitar Hero button presser!",
  "Stronger than a Wii Sports bowling champion!",
  "Has that Dance Dance Revolution foot coordination!",
  "More creative than a LittleBigPlanet level designer!",
  "Cooler than a Club Penguin igloo decorator!",
  "Has that Flappy Bird pipe dodging reflexes!",
  "More determined than a Dark Souls death counter!",
  "Stronger than a Pokémon GO step counter!",
  "Has that Subway Surfers endless running stamina!",
  "Elevator expert elite!",
  "Propeller pitch perfectionist!",
  "Mixture management master!",
  "Cowl flap controller!",
  "Fuel pump professional!",
  "Magneto switching specialist!",
  "Carb heat handler!",
  "Oil pressure observer!",
  "Engine temperature tracker!",
  "Electrical system expert!",
  "Hydraulic pressure hero!",
  "Vacuum system virtuoso!",
  "Pitot tube protector!",
  "Static port specialist!",
  "Altimeter adjusting ace!",
  "Compass calibration king!",
  "VOR navigation ninja!",
  "ILS approach artist!",
  "GPS guidance guru!",
  "DME distance detective!",
  "ADF bearing boss!",
  "Transponder code genius!",
  "Comm radio rockstar!",
  "Ground control groupie!",
  "Tower frequency finder!",
  "Approach control ace!",
  "Departure procedure pro!",
  "En route expert elite!",
  "Class airspace ambassador!",
  "NOTAM knowledge ninja!",
  "TFR tracking tactician!",
  "Weather briefing boss!",
  "Flight planning phenom!",
  "Weight balance wizard!",
  "Performance chart champion!",
  "Density altitude detective!",
  "Wind triangle warrior!",
  "Cross country crusader!",
  "Pattern work perfectionist!",
  "Touch and go guru!",
  "Short field specialist!",
  "Soft field sensation!",
  "Emergency landing legend!",
  "Go around genius!",
  "Missed approach master!",
  "Holding pattern hero!",
  "Steep turn tactician!",
  "Stall recovery rockstar!",
  "Spin awareness specialist!",
  "Ground reference guru!",
  "Hood time hero!",
  "Night flying ninja!",
  "Cross country commander!",
  "Solo flight superstar!",
  "Checkride champion!",
  "Blue sky explorer!",
  "Cloud hopping hero!",
  "Fried chicken expert!",
  "Pizza slice connoisseur!",
  "Sushi roll roller!",
  "Taco shell eater!",
  "Pasta noodle sipper!",
  "Cheeseburger cheeser!",
  "Pizza slice slicer!",
  "ProfessionalAir Breather!",
  "Runner of the Year!",
  "Master of Starting Engines!",
  "Professional sock matcher!",
  "Expert toilet paper replacer!",
  "Legendary coffee sipper!",
  "Certified sleep position adjustor!",
  "Master doorknob turner!",
  "Elite sandwich construction engineer!",
  "Professional gravity tester!",
  "Champion eyeblink coordinator!",
  "Seasoned breakfast cereal analyst!",
  "Expert refrigerator door opener!",
  "Certified walking on ground specialist!",
  "Professional breathing rhythm maintainer!",
  "Master of sitting in chairs!",
  "Elite water drinker extraordinaire!",
  "Champion phone screen toucher!",
  "Professional nose itch scratcher!",
  "Expert shoelace tier!",
  "Legendary microwave button presser!",
  "Certified pen cap clicker!",
  "Master of turning pages!",
  "Professional yawn executor!",
  "Elite finger nail grower!",
  "Champion hair follicle supporter!",
  "Expert light switch flipper!",
  "Seasoned doormat stepper!",
  "Professional alarm clock ignorer!",
  "Master of fork twirling!",
  "Elite napkin folder!",
  "Champion crumb collector!",
  "Expert spoon licker!",
  "Legendary salt shaker shaker!",
  "Certified ice cube maker!",
  "Professional leftover reheater!",
  "Master of snack bag opening!",
  "Elite kitchen timer waiter!",
  "Champion dish soap squirter!",
  "Expert tupperware lid finder!",
  "Seasoned grocery cart pusher!",
  "Professional receipt crumpler!",
  "Master of couch cushion fluffer!",
  "Elite remote control button pusher!",
  "Champion pet food pourer!",
  "Expert shoelace untier!",
  "Legendary sock puller-upper!",
  "Certified blanket adjuster!",
  "Professional pillow fluffer!",
  "Master of drawer closer!",
  "Elite ceiling starer!",
  "Champion floor walker!",
  "Expert of existing in space!",
  "Champion of build optimization calculator!",
  "Professional meta game researcher!",
  "Expert tier list memorizer!",
  "Master of patch note reader!",
  "Elite update download waiter!",
  "Champion of hotfix appreciator!",
  "Professional bug report submitter!",
  "Expert glitch exploitation artist!",
  "Master of speedrun technique student!",
  "Elite any% completion specialist!",
  "Champion of 100% perfectionist!",
  "Professional no death run attempter!",
  "Expert pacifist route explorer!",
  "Master of genocide run completer!",
  "Elite true ending discoverer!",
  "Champion of secret boss finder!",
  "Professional easter egg hunter!",
  "Expert developer room visitor!",
  "Master of debug mode activator!",
  "Elite cheat code memorizer!",
  "Champion of console command typer!",
  "Professional mod installation wizard!",
  "Expert texture pack curator!",
  "Master of shader configuration artist!",
  "Elite frame rate counter watcher!",
  "Champion of ping number analyzer!",
  "Professional server browser navigator!",
  "Expert lobby creation moderator!",
  "Master of voice chat muter!",
  "Elite text chat spammer!",
  "Champion of emote wheel",
];

export const alternator = [
  "🤖",
  "👽",
  "👾",
  "👻",
  "💀",
  "🤡",
  "🤠",
  "💊",
  "💉",
  "🩸",
  "🧬",
  "🦠",
  "🧫",
  "🧪",
  "🌡",
  "🧹",
  "🪠",
  "🧺",
  "🧻",
  "🚽",
  "🚰",
  "🚿",
  "🛁",
  "🛀",
  "🧼",
  "🪥",
  "🪒",
  "🧽",
  "🪣",
  "🧴",
  "🛎",
  "🔑",
  "🗝",
  "🚪",
  "🪑",
  "🛋",
  "🛏",
  "🛌",
  "🧸",
  "🪆",
  "🖼",
  "🪞",
  "🪟",
  "🛍",
  "🛒",
  "🎁",
  "🎈",
  "🎏",
  "🎀",
  "🪄",
  "🪅",
  "🎊",
  "🎉",
  "🪩",
  "🎎",
  "🏮",
  "🎐",
  "🧧",
  "✉️",
  "📩",
  "📨",
  "📧",
  "💌",
  "📥",
  "📤",
  "📦",
  "🐦‍🔥",
  "🍋‍🟩",
  "🍄‍🟫",
  "🚗",
  "🚕",
  "🚙",
  "🚌",
  "🚎",
  "🏎",
  "🚓",
  "🚑",
  "🚒",
  "🚐",
  "🛻",
  "🚚",
  "🚛",
  "🚜",
  "🦯",
  "🦽",
  "🦼",
  "🛴",
  "🚲",
  "🛵",
  "🏍",
  "🛺",
  "🚨",
  "🚔",
  "🚍",
  "🚘",
  "🚖",
  "🛞",
  "🚡",
  "🚠",
  "🚟",
  "🚃",
  "🚋",
  "🚞",
  "🚝",
  "🚄",
  "🚅",
  "🚈",
  "🚂",
  "🚆",
  "🚇",
  "🚊",
  "🚉",
  "🛩",
  "💺",
  "🛰",
  "🚀",
  "🛸",
  "🚁",
  "🛶",
  "⛵️",
  "🚤",
  "🛥",
  "🛳",
  "⛴",
  "🚢",
  "⚓️",
  "🛟",
  "🪝",
  "⛽️",
  "🚧",
  "🚦",
  "🚥",
  "🚏",
  "🗺",
  "🗿",
  "🗽",
  "🗼",
  "🏰",
  "🏯",
  "🏟",
  "🎡",
  "🎢",
  "🛝",
  "🎠",
  "⛲️",
  "⛱",
  "🏖",
  "🏝",
  "🏜",
  "🌋",
  "⛰",
  "🏔",
  "🗻",
  "🏕",
  "⛺️",
  "🛖",
  "🏠",
  "🏡",
  "🏘",
  "🏚",
  "🏗",
  "🏭",
  "🏢",
  "🏬",
  "🏣",
  "🏤",
  "🏥",
  "🏦",
  "🏨",
  "🏪",
  "🏫",
  "🏩",
  "💒",
  "🏛",
  "⛪️",
  "🕌",
  "🕍",
  "🛕",
  "👽",
  "💩",
  "🤮",
  "🚶‍➡️",
  "🤢",
  "🤧",
  "🤒",
  "🤕",
  "🤑",
  "🤓",
  "🤔",
  "🤕",
  "👀",
  "🥶",
  "🌭",
  "🍔",
  "🐸",
  "👹",
  "😹",
  "🤯",
  "😮‍💨",
  "😘",
  "⛽️",
  "🐶",
  "🐱",
  "🐭",
  "🐹",
  "🐰",
  "🦊",
  "🐻",
  "🐼",
  "🐨",
  "🐯",
  "🦁",
  "🐮",
  "🐷",
  "🐸",
  "🐵",
  "🐔",
  "🐧",
  "🐦",
  "🐤",
  "🦆",
  "🦅",
  "🦉",
  "🦇",
  "🐺",
  "🐗",
  "🐴",
  "🦄",
  "🐝",
  "🪱",
  "🐛",
  "🦋",
  "🐌",
  "🐞",
  "🐜",
  "🦂",
  "🦟",
  "🦗",
  "🕷️",
  "🕸️",
  "🐢",
  "🐍",
  "🦎",
  "🦖",
  "🦕",
  "🐙",
  "🦑",
  "🦐",
  "🦞",
  "🦀",
  "🐡",
  "🐠",
  "🐟",
  "🐬",
  "🐳",
  "🐋",
  "🦈",
  "🐊",
  "🐅",
  "🐆",
  "🦓",
  "🍏",
  "🍎",
  "🍐",
  "🍊",
  "🍋",
  "🍌",
  "🍉",
  "🍇",
  "🍓",
  "🫐",
  "🥝",
  "🍍",
  "🥭",
  "🥥",
  "🥑",
  "🍆",
  "🥔",
  "🥕",
  "🌽",
  "🌶️",
  "🫑",
  "🥒",
  "🥬",
  "🥦",
  "🧄",
  "🧅",
  "🍄",
  "🥜",
  "🌰",
  "🍞",
  "🥐",
  "🥖",
  "🫓",
  "🥨",
  "🥯",
  "🥞",
  "🧇",
  "🧀",
  "🍖",
  "🍗",
  "🥩",
  "🥓",
  "🍔",
  "🍟",
  "🍕",
  "🌭",
  "🥪",
  "🌮",
  "🌯",
  "🫔",
  "🥙",
  "🧆",
  "🥘",
  "🍲",
  "🍝",
  "🍜",
  "🍛",
  "🍣",
  "🍱",
  "🥟",
  "🦪",
  "🍤",
  "🍚",
  "🍘",
  "🍥",
  "🥠",
  "🥮",
  "🍢",
  "🍡",
  "🍧",
  "🍨",
  "🍦",
  "🥧",
  "🍰",
  "🪽",
  "🪶",
  "🐓",
  "🦃",
  "🦤",
  "🦚",
  "🦜",
  "🦢",
  "🪿",
  "🦩",
  "🕊",
  "🐇",
  "🦝",
  "🦨",
  "🦡",
  "🦫",
  "🦦",
  "🦥",
  "🐁",
  "🐀",
  "🐿",
  "🦔",
  "🐾",
  "🐉",
  "🐲",
  "🐦‍🔥",
  "🌵",
  "🎄",
  "🌲",
  "🌳",
  "🪾",
  "🌴",
  "🪹",
  "🪺",
  "🪵",
  "🌱",
  "🌿",
  "☘️",
  "🍀",
  "🎍",
  "🪴",
  "🎋",
  "🍃",
  "🍂",
  "🍁",
  "🍄",
  "🍄‍🟫",
  "🐚",
  "🪨",
  "🌾",
  "💐",
  "🌷",
  "🪷",
  "🌹",
  "🥀",
  "🌺",
  "🌸",
  "🪻",
  "🌼",
  "🌻",
  "🌞",
  "🌝",
  "🌛",
  "🌜",
  "🌚",
  "🌖",
  "🌗",
  "🌘",
  "🌑",
  "🌒",
  "🌓",
  "🌔",
  "🌙",
  "🌎",
  "🌍",
  "🌏",
  "🪐",
  "💫",
  "⭐️",
  "🌟",
  "✨",
  "⚡️",
  "🌕",
  " 💥",
  "🔥",
  "🌪",
  "🌈",
  "🌤",
  "⛅️",
  "🌥",
  "🌦",
  "🌧",
  "⛈",
  "🌩",
  "🌨",
  "❄️",
  "☃️",
  "⛄️",
  "🌬",
  "💨",
  "💧",
  "💦",
  "🫧",
  "☔️",
  "☂️",
  "🌊",
  "🎂",
  "🧁",
  "🍮",
  "🍭",
  "🍬",
  "🍫",
  "🍿",
  "🍩",
  "🍪",
  "🥛",
  "🍼",
  "☕",
  "🫖",
  "🍵",
  "🍶",
  "🍺",
  "🍻",
  "🥂",
  "🍷",
  "🥃",
  "🍸",
  "🍹",
  "🧃",
  "🧉",
  "🧊",
  "💻",
  "🖥️",
  "📱",
  "📲",
  "⌚",
  "⌨️",
  "🖱️",
  "🖲️",
  "🕹️",
  "💽",
  "💾",
  "💿",
  "📀",
  "📼",
  "📷",
  "📸",
  "📹",
  "🎥",
  "📽️",
  "🎞️",
  "📞",
  "☎️",
  "📟",
  "📠",
  "📺",
  "📻",
  "🎙️",
  "🎚️",
  "🎛️",
  "🧭",
  "⏰",
  "⏱️",
  "⏲️",
  "🕰️",
  "🌡️",
  "🧱",
  "🔋",
  "🔌",
  "💡",
  "🔦",
  "🕯️",
  "🧯",
  "🛢️",
  "💸",
  "💵",
  "💴",
  "💶",
  "💷",
  "💳",
  "🧾",
  "✈️",
  "💺",
  "🛣️",
  "⚽️",
  "🏀",
  "🏈",
  "⚾️",
  "🥎",
  "🎾",
  "🏐",
  "🏉",
  "🥏",
  "🎱",
  "🪀",
  "🏓",
  "🏸",
  "🏒",
  "🏑",
  "🥍",
  "🏏",
  "🪃",
  "🥅",
  "⛳️",
  "🪁",
  "🏹",
  "🎣",
  "🤿",
  "🥊",
  "🥋",
  "🎽",
  "🛹",
  "🛼",
  "🛷",
  "⛸",
  "🥌",
  "🎿",
  "⛷",
  "🏂",
  "🪂",
  "🏋️‍♀️",
  "🏋️",
  "🏋️‍♂️",
  "🤼‍♀️",
  "🤼",
  "🤼‍♂️",
  "🤸‍♀️",
  "🤸",
  "🤸‍♂️",
  "⛹️‍♀️",
  "⛹️",
  "⛹️‍♂️",
  "🤺",
  "🤾‍♀️",
  "🤾",
  "🤾‍♂️",
  "🏌️‍♀️",
  "🏌️",
  "🏌️‍♂️",
  "🏇",
  "🏄‍♀️",
  "🏄",
  "🏄‍♂️",
  "🏊‍♀️",
  "🏊",
  "🏊‍♂️",
  "🤽‍♀️",
  "🤽",
  "🤽‍♂️",
  "🚣‍♀️",
  "🚣",
  "🚣‍♂️",
  "🧗‍♀️",
  "🧗",
  "🧗‍♂️",
  "🚵‍♀️",
  "🚵",
  "🚵‍♂️",
  "🚴‍♀️",
  "🚴",
  "🚴‍♂️",
  "🏆",
  "🥇",
  "🥈",
  "🥉",
  "🏅",
  "🎖",
  "🏵",
  "🎗",
  "🎫",
  "🎟",
  "🎪",
  "🤹",
  "🤹‍♂️",
  "🤹‍♀️",
  "🎭",
  "🩰",
  "🎨",
  "🎬",
  "🎤",
  "🎧",
  "🎼",
  "🎹",
  "🥁",
  "🪘",
  "🪇",
  "🎷",
  "🎺",
  "🪗",
  "🎸",
  "🪕",
  "🎻",
  "🪈",
  "🎲",
  "♟",
  "🎯",
  "🎳",
  "🎮",
  "🎰",
  "🧩",

  ];

export const customUserImages = [
  {
    // IFLYTICS USER
      id: 1,
      role: "user",
      username: "jovictasor",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jovictasor/288/1064305_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 2,
      role: "user",
      username: "rulizalhafizh",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/rulizalhafizh/288/1061097_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 3,
      role: "user",
      username: "Afiif",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/afiif/288/851863_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 4,
      role: "user",
      username: "Saf",
    image:
      "https://cdn.discordapp.com/emojis/1362740681533165709.webp?size=240",
    },
  {
    // TEST USER
      id: 5,
      role: "user",
      username: "Mike_Lima_Tango",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/mike_lima_tango/288/1456850_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 6,
      role: "user",
      username: "Veloist",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/veloist/288/1509072_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 7,
      role: "user",
      username: "M1llard",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/m1llard/288/1479962_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 8,
      role: "user",
      username: "harrybanty",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/harrybanty/288/1458584_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 9,
      role: "user",
      username: "IF_Pramana",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/if_pramana/288/999869_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 10,
      role: "user",
      username: "Sevii",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/sevii/288/1511040_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 11,
      role: "user",
      username: "VanillaCakePeople",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/vanillacakepeople/288/481666_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 12,
      role: "user",
      username: "ka77",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/ka77/288/1408120_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 13,
      role: "user",
      username: "Provensound",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/provensound/288/1519108_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 14,
      role: "user",
      username: "CypTic",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/cyptic/288/1283542_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 15,
      role: "user",
      username: "Magician",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/magician/288/1497105_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // TEST USER
      id: 16,
      role: "user",
      username: "Keanu-X",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/keanu-x/288/1495483_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 17,
      role: "user",
      username: "YU_KIMMI",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/yu_kimmi/288/1453760_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 18,
      role: "user",
      username: "BennyBoy_Alpha",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/bennyboy_alpha/288/1479084_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 19,
      role: "user",
      username: "mara_sumera",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/mara_sumera/288/1519951_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 20,
      role: "user",
      username: "TheGlobalAviator",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/theglobalaviator/288/1382814_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 21,
      role: "user",
      username: "ThomasR",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/thomasr/288/1530166_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 22,
      role: "user",
      username: "Hilo29",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/hilo29/288/1361670_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 23,
      role: "user",
      username: "Moch_fachri",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/moch_fachri/288/1427049_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 24,
      role: "user",
      username: "Eggs_Aviation",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/eggs_aviation/288/1417588_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 25,
      role: "user",
      username: "Random_AviatorYT",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/random_aviatoryt/288/1522848_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 26,
      role: "user",
      username: "XAN_CRUSHER",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/xan_crusher/288/1465629_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 27,
      role: "user",
      username: "SebZero",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/sebzero/288/1510090_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 28,
      role: "user",
      username: "falcon.ccp",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/falcon.ccp/288/1447565_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 29,
      role: "user",
      username: "JeppyG",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jeppyg/288/1434629_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 30,
      role: "user",
      username: "Daniel_Vijay",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/daniel_vijay/288/1463558_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 31,
      role: "user",
      username: "CaptGerry",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/captgerry/288/1265547_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 32,
      role: "user",
      username: "footmonk",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/footmonk/288/1526669_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 33,
      role: "user",
      username: "Ronny_Schubert",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/ronny_schubert/288/1407339_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 34,
      role: "user",
      username: "IFPHG-Andrino",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/ifphg-andrino/288/1530079_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 35,
      role: "user",
      username: "iJazzyman",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/ijazzyman/288/402078_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 36, 
      role: "user",
      username: "JONKRUX",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jonkrux/288/1526377_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 37,
      role: "user",
      username: "Daeng-E",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/daeng-e/288/1498655_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 38,
      role: "user",
      username: "charlesacosta163",
    image: `https://images.weserv.nl/?url=https%3A%2F%2Fsea1.discourse-cdn.com%2Finfiniteflight%2Fuser_avatar%2Fcommunity.infiniteflight.com%2Fcharlesacosta163%2F288%2F509744_2.png&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 39,
      role: "user",
      username: "KhamaniAviationYT",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/khamaniaviationyt/288/525536_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 40,
      role: "user",
      username: "Bank",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/bank/288/1426438_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 41,
      role: "user",
      username: "Hardeep_Pannu",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/hardeep_pannu/288/1367980_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 42,
      role: "user",
      username: "Cwaker",   
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/cwaker/288/1513293_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 43,
      role: "user",
      username: "UTTKARSH_SINGH",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/uttkarsh_singh/288/1433492_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 44,
      role: "user",
      username: "3Ssomy167",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/3ssomy167/288/1438322_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 45,
      role: "user",
      username: "Captsairol",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/captsairol/288/1516967_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    }, 
  {
    // IFLYTICS USER
      id: 46,
      role: "user",
      username: "Darmawan",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/darmawan/288/1470558_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 47,
      role: "user",
      username: "AviatorChina",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/aviatorchina/288/1484825_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 48,
      role: "user",
      username: "Abhik_Mallik",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/abhik_mallik/288/1519711_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // IFLYTICS USER
      id: 49,
      role: "user",
      username: "Avboy_Mohammed6",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/avboy_mohammed6/288/1496130_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 50,
      role: "staff",
      username: "Cameron",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/cameron/288/886772_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 51,
      role: "staff",
      username: "Schyllberg",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/schyllberg/288/1423541_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 52,
      role: "staff",
      username: "Laura",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/laura/288/879474_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 53,
      role: "staff",
      username: "Tyler_Shelton",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/tyler_shelton/288/564447_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 54,
      role: "staff",
      username: "jasonrosewell",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jasonrosewell/288/1523240_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 55,
      role: "staff",
      username: "Jan",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jan/288/1363021_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 56,
      role: "staff",
      username: "Dan",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/dan/288/1370793_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 57,
      role: "staff",
      username: "philippe",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/philippe/288/4_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 58,
      role: "staff",
      username: "A-FitzGerald",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/a-fitzgerald/288/513779_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 59,
      role: "staff",
      username: "jarno80",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jarno80/288/57776_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
    },
  {
    // STAFF
      id: 60,
      role: "staff",
      username: "AdamCallow",
    image: `https://images.weserv.nl/?url=https%3A//sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/adamcallow/288/1098129_2.png&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 61,
    role: "user",
    username: "CaptainDinglehopper",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/captaindinglehopper/288/664951_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 62,
    role: "user",
    username: "BenR22",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/benr22/288/1504790_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 63,
    role: "user",
    username: "CQSamuelCai",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/cqsamuelcai/288/1324946_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 64,
    role: "user",
    username: "Mrp_98",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/mrp_98/288/1490886_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 65,
    role: "user",
    username: "MagiK",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/magik/288/1376513_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 66,
    role: "user",
    username: "JH_AVIATION",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jh_aviation/288/1524047_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 67,
    role: "user",
    username: "Shaun0312",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/shaun0312/288/1266749_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 68,
    role: "user",
    username: "IF.Russian",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/if.russian/288/1482824_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 69,
    role: "user",
    username: "Chuck4D22",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/chuck4d22/288/1476855_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 70,
    role: "user",
    username: "FreshOuttaPoland",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/freshouttapoland/288/1504687_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 71,
    role: "user",
    username: "Magicalchesecat",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/magicalchesecat/288/1455691_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // IFLYTICS USER
    id: 72,
    role: "user",
    username: "Guest",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/guest/288/1222656_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  },
  {
    // MODERATOR INFINITE FLIGHT
    id: 73,
    role: "mod",
    username: "Trey",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/trey/288/1498977_2.png")}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 74,
    role: "mod",
    username: "Chris_S",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/chris_s/288/1233089_2.png")}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 75,
    role: "mod",
    username: "Asher",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/asher/288/885244_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 76,
    role: "mod",
    username: "Darius_Glover",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/darius_glover/288/1006755_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 77,
    role: "mod",
     username: "tomthetank",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/tomthetank/144/1104903_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
  // MODERATOR INFINITE FLIGHT
  id: 78,
  role: "mod",
  username: "Ecoops123",
  image: `https://images.weserv.nl/?url=${encodeURIComponent(
    "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/ecoops123/144/1344646_2.png"
  )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 79,
    role: "mod",
    username: "RickG",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/rickg/144/1398415_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 80,
    role: "mod",
    username: "JoshFly8",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/joshfly8/144/723737_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 81,
    role: "mod",
    username: "Jet_Airways_995",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/jet_airways_995/144/696532_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 82,
    role: "mod",
    username: "Alex",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/alex/144/1382654_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // MODERATOR INFINITE FLIGHT
    id: 83,
    role: "user",
    username: "Evan",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/evan/144/1448403_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 84,
    role: "user",
    username: "EliteExpert",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/eliteexpert/288/1528104_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 85,
    role: "user",
    username: "Avean",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://avatars.discourse-cdn.com/v4/letter/a/3bc359/96.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 86,
    role: "user",
    username: "Beluga1",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/beluga1/288/1533701_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 87,
    role: "user",
    username: "Riley_Dupont",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/riley_dupont/288/1437814_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 88,
    role: "user",
    username: "Aviation_Xiao",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/aviation_xiao/288/1498989_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 89,
    role: "user",
    username: "Sonila_Llupo",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/sonila_llupo/288/916868_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 90,
    role: "user",
    username: "Guimieukis",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/guimieukis/288/1515543_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 91,
    role: "user",
    username: "yoshi_flyer",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/yoshi_flyer/288/1533161_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 92,
    role: "user",
    username: "Lopes",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/lopes/288/1523435_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 93,
    role: "user",
    username: "Carlos_Eduardo_Ferna",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/carlos_eduardo_ferna/288/1328882_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 94,
    role: "user",
    username: "CaptJJ",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/captjj/288/1221327_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 95,
    role: "user",
    username: "Patel_Mayur",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/patel_mayur/288/1251782_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 96,
    role: "user",
    username: "MoonRaiku",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/moonraiku/288/1534227_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 97,
    role: "user",
    username: "rowan",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/rowan/288/1399943_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
  {
    // IFLYTICS USER
    id: 98,
    role: "user",
    username: "your-fav-car-guy-o52",
    image: `https://images.weserv.nl/?url=${encodeURIComponent(
      "https://sea1.discourse-cdn.com/infiniteflight/user_avatar/community.infiniteflight.com/your-fav-car-guy-o52/288/1419768_2.png"
    )}&w=64&h=64&fit=cover&mask=circle`,
  }, 
];

// Unknown User Compliments - Maximum Corn Level
export const unknownUserCompliments = [
  "More mysterious than Batman's identity!",
  "Channeling main character energy!",
  "Plot armor stronger than Superman!",
  "Living their best NPC life!",
  "Has that Disney princess glow!",
  "Giving off secret agent vibes!",
  "More elusive than Bigfoot!",
  "Radiating Jedi master calm!",
  "Built different, certified iconic!",
  "Has that anime protagonist hair!",
  "Possesses Hermione-level intelligence!",
  "More legendary than a shiny Pokémon!",
  "Straight out of a Marvel origin story!",
  "Has that Netflix series potential!",
  "Cooler than the other side of the pillow!",
  "More valuable than Bitcoin in 2017!",
  "Has that TikTok famous energy!",
  "Radiating Taylor Swift confidence!",
  "More mysterious than Area 51!",
  "Living in their own rom-com!",
  "Has that Stranger Things mystery!",
  "More legendary than Chuck Norris!",
  "Possesses Thanos-level determination!",
  "Has that Keanu Reeves wholesomeness!",
  "More iconic than the iPhone!",
  "Channeling their inner Beyoncé!",
  "Has that Sherlock Holmes deduction!",
  "More powerful than a Nokia 3310!",
  "Living their Barbie dream life!",
  "Has that Gordon Ramsay passion!",
  "More legendary than a unicorn!",
  "Possesses Oprah-level generosity!",
  "More mysterious than the Bermuda Triangle!",
  "Channeling their inner superhero!",
  "Has that Friends group loyalty!",
  "More iconic than pizza on Friday!",
  "Living their Harry Potter fantasy!",
  "Has that Office manager efficiency!",
  "More legendary than Wi-Fi password!",
  "Possesses Bob Ross level zen!",
  "Has that Star Wars force sensitivity!",
  "More valuable than free shipping!",
  "Channeling their inner Disney villain!",
  "Has that Breaking Bad intensity!",
  "More mysterious than sock disappearance!",
  "Living their Game of Thrones epic!",
  "Has that Avengers assemble energy!",
  "More iconic than Monday morning coffee!",
  "Possesses that unmatched mysterious aura!",
];
    